### ISSUE TITLE
Cannot use U / ''

### ISSUE THREAD

**Issue by rubik** [Visgean/urljects#6]
It's currently impossible to use the `U / ''` syntax:

    >>> from urljects import U
    >>> U / ''
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/miki/exp/pankow/lib/python3.4/site-packages/urljects/patterns.py", line 93, in __repr__
        return self.get_value() or ''
      File "/home/miki/exp/pankow/lib/python3.4/site-packages/urljects/patterns.py", line 68, in get_value
        if value[0] != beginning:
    IndexError: string index out of range

I was wondering, is this really necessary? An alternative would be to allow just `U`.

**Comment by Visgean** [comment]
Well its necessary at the moment. I will fix this later...

**Comment by Visgean** [comment]
But in meantime you can use something like this https://github.com/WebArchivCZ/Seeder/blob/master/Seeder/urls.py#L41

**Comment by rubik** [comment]
Ok, I'll use that. I also tried `U / None` but it adds a `%2F` in the url when used with `view_include`. Example: `U / None + U / 'faq' -> /%2Ffaq` instead of `/faq`.

**Comment by Visgean** [comment]
fixed in 71f4ebc665c59c59a39eef8b706532bff05451bd

**Comment by Visgean** [comment]
Now you should be able to directly use U for wild cards.. Look to tests for more info...

**Comment by rubik** [comment]
Perfect, thanks!
